'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { ClientBoundedProvider } from '@/redux/provider/ClientBoundedProvider'
import { Session } from 'next-auth'
import NextAuthSessionProvider from './utils/NextAuthSessionProvider/NextAuthSessionProvider'

//LAYOUT jet plikiem, który zawiera wspólne dla wszystkich stron aplikacji elementy tj. nawigacja lub stopka

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Login and dash',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
  session:Session
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <ClientBoundedProvider>
            {children}          
          </ClientBoundedProvider>          
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
