import './login.css'
import { Inter } from 'next/font/google'

//LAYOUT jet plikiem, który zawiera wspólne dla wszystkich stron aplikacji elementy tj. nawigacja lub stopka

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
